version: "3.9"
services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./Flight-trackerBE
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
      - ./Flight-trackerBE:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_DB=flight_tracker"
      - "POSTGRES_USER=samady"
      - "POSTGRES_PASSWORD=f_tracker123"
    volumes:
      - pgdata:/var/lib/postgresql/data
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./Flight-trackerFE
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./Flight-trackerFE:/app
volumes:
  pgdata:
